### ISSUE TITLE
Middleware

### ISSUE THREAD

**Issue by blitzprog** [blitzprog/aero#21]
We need a middleware architecture.
Middleware that works with frameworks like Express should work with Aero as well.

**Comment by amitguptagwl** [comment]
Is there any documentation how to use the middleware?

**Comment by akyoto** [comment]
https://github.com/aerojs/aero/blob/nodejs/docs/API.md#middleware

**Comment by amitguptagwl** [comment]
Great thanks. Then I believe this is the answer for #101 as well?

**Comment by akyoto** [comment]
Yes, `use` or `rewrite`, both register handlers that are executed before the final response. `use` is more appropriate, I believe.

**Comment by amitguptagwl** [comment]
yup, let me try. thanks a lot.
